services:
  vibevoice-realtime-openai-api:
    build: .
    image: vibevoice-realtime-openai-api
    container_name: vibevoice-realtime-openai-api
    ports:
      - "8880:8880"
    volumes:
      - ./models:/home/ubuntu/app/models
      - ./vibevoice_realtime_openai_api.py:/home/ubuntu/app/vibevoice_realtime_openai_api.py:ro
    environment:
      - CFG_SCALE=1.25  # (0.0 - 3.0, higher = more expressive)
      - VIBEVOICE_DEVICE=cpu
      - OPTIMIZE_FOR_SPEED=0
    restart: unless-stopped
